include: package:dart_frog_lint/recommended.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    avoid_print: ignore
    lines_longer_than_80_chars: ignore
    prefer_inlined_adds: ignore
    cascade_invocations: ignore
